"""poc

Revision ID: 114586f210b8
Revises: 5909ee33095c
Create Date: 2022-08-19 07:35:25.865264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "114586f210b8"
down_revision = "5909ee33095c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("joby_todo_task_parents", sa.Column("root_id", postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, "joby_todo_task_parents", "joby_todo_task", ["root_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "joby_todo_task_parents", type_="foreignkey")
    op.drop_column("joby_todo_task_parents", "root_id")
    # ### end Alembic commands ###
